const memoryStore = {
  users: [
    {
      _id: 'user-student-1',
      name: 'Shikhar (Student)',
      email: 'student@disasterchain.org',
      password: 'student123',
      role: 'student',
      isVerified: true,
    },
    {
      _id: 'user-admin-1',
      name: 'Chief Disaster Officer',
      email: 'admin@disasterchain.org',
      password: 'admin123',
      role: 'admin',
      isVerified: true,
    },
  ],
  sosRequests: [
    {
      _id: 'sos-1',
      requestId: 'SOS-1042',
      name: 'Aarav Sharma',
      emergencyType: 'Medical Emergency',
      description: 'Elderly person suffering severe asthma attack due to fire smoke inhalation. Needs oxygen support.',
      location: 'Block C, Sector 14, North Campus',
      peopleAffected: 2,
      severity: 'Critical',
      contact: '+91 98765 43210',
      status: 'In Progress',
      createdAt: new Date(),
    },
    {
      _id: 'sos-2',
      requestId: 'SOS-1043',
      name: 'Pooja Verma',
      emergencyType: 'Flood',
      description: 'Ground floor submerged in 4 feet water. 5 students trapped on terrace with no drinking water.',
      location: 'Girls Hostel 3, River View Road',
      peopleAffected: 5,
      severity: 'High',
      contact: '+91 98111 22334',
      status: 'Assigned',
      createdAt: new Date(),
    },
    {
      _id: 'sos-3',
      requestId: 'SOS-1044',
      name: 'Rohan Gupta',
      emergencyType: 'Building Damage',
      description: 'Cracks appeared on staircase wall after tremor; emergency exit door jammed.',
      location: 'Main Science Complex, Wing B',
      peopleAffected: 12,
      severity: 'High',
      contact: '+91 98222 33445',
      status: 'Pending',
      createdAt: new Date(),
    },
    {
      _id: 'sos-4',
      requestId: 'SOS-1045',
      name: 'Sunita Patel',
      emergencyType: 'Fire',
      description: 'Short circuit fire spreading in chemistry lab corridor on 2nd floor.',
      location: 'Academic Block 4, South Campus',
      peopleAffected: 8,
      severity: 'Critical',
      contact: '+91 98333 44556',
      status: 'In Progress',
      createdAt: new Date(),
    },
    {
      _id: 'sos-5',
      requestId: 'SOS-1046',
      name: 'Kunal Sen',
      emergencyType: 'Trapped Person',
      description: 'Elevator stopped between 3rd and 4th floors due to power outage.',
      location: 'Central Library Tower',
      peopleAffected: 3,
      severity: 'Medium',
      contact: '+91 98444 55667',
      status: 'Resolved',
      createdAt: new Date(),
    },
  ],
  shelters: [
    {
      _id: 'sh-1',
      name: 'Central University Indoor Stadium Shelter',
      address: 'Sports Complex, University Campus',
      latitude: 28.6139,
      longitude: 77.2090,
      capacity: 600,
      occupancy: 380,
      facilities: ['Food', 'Drinking Water', 'Medical Support', 'Electricity', 'Sleeping Area', 'Toilets'],
      status: 'Open',
      phone: '+91 11 2345 6780',
    },
    {
      _id: 'sh-2',
      name: 'Community Relief Center Sector 9',
      address: 'Opposite Civil Hospital, Sector 9',
      latitude: 28.6250,
      longitude: 77.2180,
      capacity: 400,
      occupancy: 400,
      facilities: ['Food', 'Drinking Water', 'Medical Support', 'Electricity', 'Toilets'],
      status: 'Full',
      phone: '+91 11 2345 6781',
    },
    {
      _id: 'sh-3',
      name: 'Government Model Senior School Shelter',
      address: 'Ring Road, North Campus Extension',
      latitude: 28.6350,
      longitude: 77.2010,
      capacity: 350,
      occupancy: 120,
      facilities: ['Food', 'Drinking Water', 'Electricity', 'Sleeping Area', 'Toilets'],
      status: 'Open',
      phone: '+91 11 2345 6782',
    },
    {
      _id: 'sh-4',
      name: 'Red Cross Emergency Transit Shelter',
      address: 'Near Railway Station Gate 2',
      latitude: 28.6050,
      longitude: 77.2150,
      capacity: 250,
      occupancy: 85,
      facilities: ['Drinking Water', 'Medical Support', 'Internet', 'Toilets'],
      status: 'Open',
      phone: '+91 11 2345 6783',
    },
    {
      _id: 'sh-5',
      name: 'City Youth Center Emergency Camp',
      address: 'Green Park, Block B',
      latitude: 28.5950,
      longitude: 77.2250,
      capacity: 500,
      occupancy: 210,
      facilities: ['Food', 'Drinking Water', 'Medical Support', 'Electricity', 'Sleeping Area'],
      status: 'Open',
      phone: '+91 11 2345 6784',
    },
  ],
  affectedAreas: [
    {
      _id: 'area-1',
      name: 'North Riverfront Zone',
      disasterType: 'Flood / Inundation',
      severity: 'Critical',
      description: 'Water level exceeded danger mark by 1.8m. Low-lying residential hostels submerged.',
      affectedPeople: 2400,
      activeSOS: 14,
      status: 'Active',
    },
    {
      _id: 'area-2',
      name: 'Old Campus Science Enclave',
      disasterType: 'Structural Hazard',
      severity: 'High',
      description: 'Seismic tremors caused wall fractures; power lines disconnected.',
      affectedPeople: 850,
      activeSOS: 6,
      status: 'Active',
    },
    {
      _id: 'area-3',
      name: 'Industrial Sector 5',
      disasterType: 'Chemical / Smoke Hazard',
      severity: 'Moderate',
      description: 'Localized warehouse fire emitting dense smoke. Air quality index at hazardous levels.',
      affectedPeople: 1200,
      activeSOS: 3,
      status: 'Controlled',
    },
    {
      _id: 'area-4',
      name: 'Eastern Hill Slope',
      disasterType: 'Landslide Risk',
      severity: 'High',
      description: 'Heavy rain triggered soil erosion near university perimeter wall.',
      affectedPeople: 450,
      activeSOS: 2,
      status: 'Active',
    },
    {
      _id: 'area-5',
      name: 'Central Marketplace',
      disasterType: 'Urban Waterlogging',
      severity: 'Low',
      description: 'Storm drain overflow cleared; municipal pumps operational.',
      affectedPeople: 300,
      activeSOS: 0,
      status: 'Recovering',
    },
  ],
  alerts: [
    {
      _id: 'alt-1',
      title: 'CRITICAL: Severe Flood Warning for North Riverfront',
      message: 'River levels rising rapidly. Evacuate ground floor quarters immediately to Central Indoor Stadium Shelter.',
      type: 'Flood',
      severity: 'Critical',
      location: 'North Campus & Riverfront Zone',
      active: true,
      createdAt: new Date(),
    },
    {
      _id: 'alt-2',
      title: 'DANGER: Fire Safety Advisory — Academic Block 4',
      message: 'Firefighting teams actively extinguishing corridor blaze. Avoid Academic Block 4 and keep access roads clear.',
      type: 'Fire',
      severity: 'Danger',
      location: 'Academic Block 4, South Campus',
      active: true,
      createdAt: new Date(),
    },
    {
      _id: 'alt-3',
      title: 'WARNING: Heavy Thunderstorm & High Winds Forecast',
      message: 'Wind gusts up to 75 km/h predicted. Stay indoors and do not stand under weak trees or power lines.',
      type: 'Thunderstorm',
      severity: 'Warning',
      location: 'Entire Campus Region',
      active: true,
      createdAt: new Date(),
    },
    {
      _id: 'alt-4',
      title: 'INFO: Safe Drinking Water Distribution Station Open',
      message: 'Clean potable drinking water packets available at Student Center Helpdesk.',
      type: 'General',
      severity: 'Information',
      location: 'Student Activity Center',
      active: true,
      createdAt: new Date(),
    },
  ],
  incidents: [
    {
      _id: 'inc-1',
      incidentId: 'INC-2041',
      title: 'Emergency Exit Door Jammed with Debris',
      type: 'Blocked emergency exit',
      description: 'Construction wooden planks and discarded furniture blocking the rear emergency fire escape door in hostel 2.',
      severity: 'High',
      location: 'Hostel 2, Ground Floor Rear Exit',
      reporterName: 'Shikhar (Student)',
      status: 'Under Review',
      createdAt: new Date(),
    },
    {
      _id: 'inc-2',
      incidentId: 'INC-2042',
      title: 'Sparking Exposed Electrical Transformer',
      type: 'Damaged electrical equipment',
      description: 'Water dripping onto main step-down transformer next to cafeteria creating sparking and smoke.',
      severity: 'Critical',
      location: 'Cafeteria Junction Substation',
      reporterName: 'Ananya Roy',
      status: 'Pending',
      createdAt: new Date(),
    },
    {
      _id: 'inc-3',
      incidentId: 'INC-2043',
      title: 'Large Banyan Tree Branch Fallen on Access Road',
      type: 'Fallen tree',
      description: 'Heavy wind snapped 15-meter branch blocking ambulance route toward University Health Center.',
      severity: 'Medium',
      location: 'Health Center Roadway',
      reporterName: 'Ravi Teja',
      status: 'Resolved',
      createdAt: new Date(),
    },
  ],
  resources: [
    {
      _id: 'res-1',
      name: 'Apex Civil Hospital & Trauma Center',
      type: 'Hospital',
      address: 'Plot 12, Medical Square, Civil Lines',
      phone: '+91 11 2233 4455',
      description: '24/7 Emergency trauma care, burn ICU, blood bank, and 6 ambulance units.',
      status: 'Operational',
    },
    {
      _id: 'res-2',
      name: 'University Health & First Aid Clinic',
      type: 'Medical Center',
      address: 'Student Amenities Block, Gate 1',
      phone: '+91 11 2345 6701',
      description: 'Campus emergency doctors, triage beds, first aid supplies, and oxygen concentrators.',
      status: 'Operational',
    },
    {
      _id: 'res-3',
      name: 'City Fire Station No. 4',
      type: 'Fire Station',
      address: 'Ring Road By-pass, Near North Gate',
      phone: '+91 11 101',
      description: 'Equipped with 4 hydraulic fire tenders, rescue cutters, and HAZMAT teams.',
      status: 'Operational',
    },
    {
      _id: 'res-4',
      name: 'Campus Police Station & PCR Control',
      type: 'Police Station',
      address: 'Main Administrative Circle',
      phone: '+91 11 112',
      description: 'Disaster response coordination, law enforcement, crowd control, and patrol vans.',
      status: 'Operational',
    },
    {
      _id: 'res-5',
      name: 'District Disaster Management Authority (DDMA)',
      type: 'Disaster Management Office',
      address: 'Collectorate Complex, Block B',
      phone: '+91 11 2392 3456',
      description: 'Government apex coordination unit for disaster alerts and NDRF deployment.',
      status: 'Operational',
    },
    {
      _id: 'res-6',
      name: 'Red Cross Relief Warehouse',
      type: 'Relief Center',
      address: 'Sector 15 Logistics Hub',
      phone: '+91 11 2371 6441',
      description: 'Central stockpile of emergency ration kits, blankets, hygiene packs, and tarpaulins.',
      status: 'Operational',
    },
    {
      _id: 'res-7',
      name: 'Community Food Kitchen & Water Base',
      type: 'Food Distribution Center',
      address: 'Community Hall, Sector 8',
      phone: '+91 11 2345 8899',
      description: 'Distributes 3,000 cooked meal packets daily and operates 4 potable water tankers.',
      status: 'Operational',
    },
    {
      _id: 'res-8',
      name: 'St. John Ambulance Rapid Response Squad',
      type: 'Medical Center',
      address: 'Near Metro Station Gate 3',
      phone: '+91 11 2345 7766',
      description: 'Mobile paramedical vans with trained student volunteers and stretcher teams.',
      status: 'Operational',
    },
    {
      _id: 'res-9',
      name: 'Central University Indoor Stadium Shelter',
      type: 'Emergency Shelter',
      address: 'Sports Complex, University Campus',
      phone: '+91 11 2345 6780',
      description: 'Large ventilated emergency shelter with beds, toilets, and food mess.',
      status: 'Operational',
    },
    {
      _id: 'res-10',
      name: 'State Disaster Response Force (SDRF) Post',
      type: 'Disaster Management Office',
      address: 'Boat Club, Riverfront East',
      phone: '+91 11 2345 9900',
      description: 'Equipped with motorized inflatable rescue boats and flood scuba divers.',
      status: 'Operational',
    },
  ],
  donations: [
    {
      _id: 'don-1',
      donationId: 'DON-3011',
      donor: 'Tata Relief Trust & Alumni Network',
      type: 'Medical Supplies',
      resourceName: 'Emergency First-Aid Kits & Antibiotics',
      quantity: 1200,
      unit: 'kits',
      destination: 'Central University Indoor Stadium Shelter',
      status: 'Fully Distributed',
      blockchainTransactionId: 'TXN-881204',
      createdAt: new Date(),
    },
    {
      _id: 'don-2',
      donationId: 'DON-3012',
      donor: 'Rotary Club City Chapter',
      type: 'Food',
      resourceName: 'Ready-to-Eat Emergency Food Packets',
      quantity: 3500,
      unit: 'meals',
      destination: 'Community Food Kitchen Sector 8',
      status: 'Partially Distributed',
      blockchainTransactionId: 'TXN-881205',
      createdAt: new Date(),
    },
    {
      _id: 'don-3',
      donationId: 'DON-3013',
      donor: 'Care India Foundation',
      type: 'Water',
      resourceName: 'Packaged Drinking Water Liters',
      quantity: 5000,
      unit: 'bottles',
      destination: 'North Riverfront Zone Shelter',
      status: 'Received',
      blockchainTransactionId: 'TXN-881206',
      createdAt: new Date(),
    },
    {
      _id: 'don-4',
      donationId: 'DON-3014',
      donor: 'Student Union Relief Drive',
      type: 'Blankets',
      resourceName: 'Thermal Woolen Blankets',
      quantity: 800,
      unit: 'blankets',
      destination: 'Government Model Senior School Shelter',
      status: 'Verified',
      blockchainTransactionId: 'TXN-881207',
      createdAt: new Date(),
    },
    {
      _id: 'don-5',
      donationId: 'DON-3015',
      donor: 'Tech Innovators NGO',
      type: 'Emergency Kits',
      resourceName: 'Solar Rechargeable Flashlights & Power Banks',
      quantity: 450,
      unit: 'units',
      destination: 'Red Cross Emergency Transit Shelter',
      status: 'Registered',
      blockchainTransactionId: 'TXN-881208',
      createdAt: new Date(),
    },
  ],
  distributions: [
    {
      _id: 'dis-1',
      distributionId: 'DIS-4011',
      resourceName: 'Emergency First-Aid Kits',
      quantity: 500,
      unit: 'kits',
      source: 'Red Cross Relief Warehouse',
      destination: 'Central University Indoor Stadium Shelter',
      responsibleOrganization: 'St. John Ambulance Squad',
      status: 'Distributed',
      blockchainTransactionId: 'TXN-881204',
      createdAt: new Date(),
    },
    {
      _id: 'dis-2',
      distributionId: 'DIS-4012',
      resourceName: 'Ready-to-Eat Food Packets',
      quantity: 1500,
      unit: 'meals',
      source: 'Community Food Kitchen Sector 8',
      destination: 'North Riverfront Zone Evacuees',
      responsibleOrganization: 'NCC Relief Squad',
      status: 'Delivered',
      blockchainTransactionId: 'TXN-881205',
      createdAt: new Date(),
    },
    {
      _id: 'dis-3',
      distributionId: 'DIS-4013',
      resourceName: 'Packaged Drinking Water Bottles',
      quantity: 2000,
      unit: 'bottles',
      source: 'Red Cross Relief Warehouse',
      destination: 'Girls Hostel 3 Flood Point',
      responsibleOrganization: 'SDRF Flood Team',
      status: 'In Transit',
      blockchainTransactionId: 'TXN-881206',
      createdAt: new Date(),
    },
    {
      _id: 'dis-4',
      distributionId: 'DIS-4014',
      resourceName: 'Thermal Woolen Blankets',
      quantity: 400,
      unit: 'blankets',
      source: 'Student Union Relief Drive',
      destination: 'City Youth Center Emergency Camp',
      responsibleOrganization: 'Volunteer Corps',
      status: 'Delivered',
      blockchainTransactionId: 'TXN-881207',
      createdAt: new Date(),
    },
    {
      _id: 'dis-5',
      distributionId: 'DIS-4015',
      resourceName: 'Solar Flashlights & Power Banks',
      quantity: 200,
      unit: 'units',
      source: 'Tech Innovators NGO Depot',
      destination: 'Government Model Senior School Shelter',
      responsibleOrganization: 'Campus Taskforce',
      status: 'Planned',
      blockchainTransactionId: 'TXN-881208',
      createdAt: new Date(),
    },
  ],
  blockchainRecords: [
    {
      _id: 'bc-1',
      transactionId: 'TXN-881204',
      entityType: 'Donation',
      entityId: 'DON-3011',
      donorOrSource: 'Tata Relief Trust & Alumni Network',
      destination: 'Central University Indoor Stadium Shelter',
      resourceName: 'Emergency First-Aid Kits & Antibiotics',
      quantity: 1200,
      unit: 'kits',
      status: 'Verified',
      blockNumber: 1001,
      blockHash: '0x7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
      previousBlockHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
      signature: '0xa41c7b89d6e4f3a2b1c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6',
      timestamp: new Date(),
      verificationNote: 'Cryptographically verified relief donation registered on DisasterChain transparency ledger.',
    },
    {
      _id: 'bc-2',
      transactionId: 'TXN-881205',
      entityType: 'Donation',
      entityId: 'DON-3012',
      donorOrSource: 'Rotary Club City Chapter',
      destination: 'Community Food Kitchen Sector 8',
      resourceName: 'Ready-to-Eat Emergency Food Packets',
      quantity: 3500,
      unit: 'meals',
      status: 'Verified',
      blockNumber: 1002,
      blockHash: '0x9b4c6e82f1a3d5e7c9b0a2f4d6e8f0a2b4c6e8f0a2b4c6e8f0a2b4c6e8f0a2b4',
      previousBlockHash: '0x7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
      signature: '0xb23d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d',
      timestamp: new Date(),
      verificationNote: 'Cryptographically verified relief donation registered on DisasterChain transparency ledger.',
    },
    {
      _id: 'bc-3',
      transactionId: 'TXN-881206',
      entityType: 'Distribution',
      entityId: 'DIS-4013',
      donorOrSource: 'Red Cross Relief Warehouse',
      destination: 'Girls Hostel 3 Flood Point',
      resourceName: 'Packaged Drinking Water Bottles',
      quantity: 2000,
      unit: 'bottles',
      status: 'In Transit',
      blockNumber: 1003,
      blockHash: '0x3c5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e',
      previousBlockHash: '0x9b4c6e82f1a3d5e7c9b0a2f4d6e8f0a2b4c6e8f0a2b4c6e8f0a2b4c6e8f0a2b4',
      signature: '0xc34e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e',
      timestamp: new Date(),
      verificationNote: 'Cryptographically verified relief distribution registered on DisasterChain transparency ledger.',
    },
    {
      _id: 'bc-4',
      transactionId: 'TXN-881207',
      entityType: 'Distribution',
      entityId: 'DIS-4014',
      donorOrSource: 'Student Union Relief Drive',
      destination: 'City Youth Center Emergency Camp',
      resourceName: 'Thermal Woolen Blankets',
      quantity: 400,
      unit: 'blankets',
      status: 'Delivered',
      blockNumber: 1004,
      blockHash: '0x4d6f8a0b2c4e6f8a0b2c4e6f8a0b2c4e6f8a0b2c4e6f8a0b2c4e6f8a0b2c4e6f',
      previousBlockHash: '0x3c5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e7f9a1b3d5e',
      signature: '0xd45f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f',
      timestamp: new Date(),
      verificationNote: 'Cryptographically verified relief distribution registered on DisasterChain transparency ledger.',
    },
  ],
};

module.exports = memoryStore;
